### ISSUE TITLE
Android Background service not working 

### ISSUE THREAD

**Issue by ZFHung** [nintendaii/UnityNotifPlugin#18]
this us my Android logcat，please help me how to fix

2024-02-27 15:58:35.741  8433-8455  Unity                   pid-8433                             E  AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/content/ContextCompat;
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/content/ContextCompat;
                                                                                                    	at com.auo.unityplugin.PluginInstance.ReceiveActivityInstance(PluginInstance.java:57)
                                                                                                    	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
                                                                                                    	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
                                                                                                    	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
                                                                                                    Caused by: java.lang.ClassNotFoundException: androidx.core.content.ContextCompat
                                                                                                    	at com.auo.unityplugin.PluginInstance.ReceiveActivityInstance(PluginInstance.java:57) 
                                                                                                    	at com.unity3d.player.UnityPlayer.nativeRender(Native Method) 
                                                                                                    	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0) 
                                                                                                    	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226) 
                                                                                                    	at android.os.Looper.loop(Looper.java:313) 
                                                                                                    	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20) 
                                                                                                      at UnityEngine.AndroidJNISafe.CheckException () [0x00096] in <5ebb0610eb504545a903252b7d55fe06>:0 
                                                                                                      at UnityEngine.AndroidJNISafe.CallStaticVoidMethod (System.IntPtr clazz, System.IntPtr methodID, UnityEngine.jvalue[] args) [0

**Comment by nintendaii** [comment]
Hey, sorry this project is no longer maintained :(

**Comment by YuliyF** [comment]
((.. gueys, maybe, fix it and add to Unity store - ? I need such cool tools
